# Setup
title:               Hegel Reading Group
tagline:             ''
description:         'Hegel reading group for UW Philosophy, summer of 2023.'
url:                 http://uwphil.github.io
baseurl:             'hegel-23su'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andre Ye
  url:               https://andre-ye.github.io
  email:             andreye@uw.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
